"use client";

import { FormEvent, useEffect, useState } from "react";

type Staff = { id: string; display_name: string; role_title: string; skill_summary: string; classified_skills: string[]; skill_confidence: number | null; hourly_cost_cents: number; available: boolean };
const labels: Record<string, string> = { "general-renovation": "General renovation", "fire-water-restoration": "Fire and water restoration", painting: "Painting", drywall: "Drywall and gypsum", flooring: "Flooring", insulation: "Insulation", roofing: "Roofing", siding: "Siding and cladding", "finish-carpentry": "Finish carpentry", "doors-and-hardware": "Doors and hardware", "window-replacement": "Windows and glazing", "demolition-abatement": "Demolition and abatement", "minor-electrical": "Minor electrical", "minor-plumbing": "Minor plumbing" };
const money = (cents: number) => new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD" }).format(cents / 100);

export default function TeamPage() {
  const [staff, setStaff] = useState<Staff[]>([]);
  const [canEdit, setCanEdit] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);
  async function load() { try { const response = await fetch("/api/team"); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to load team"); setStaff(data.staff ?? []); setCanEdit(data.canEdit); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Unable to load team"); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function remove(id: string) { if (!confirm("Remove this team profile?")) return; const response = await fetch(`/api/team/${id}`, { method: "DELETE" }); if (response.ok) setStaff((current) => current.filter((member) => member.id !== id)); }
  if (loading) return <main className="empty-page"><p className="eyebrow accent">Company team</p><h1>People and skills</h1><p>Loading team profiles...</p></main>;
  if (error) return <main className="empty-page"><p className="eyebrow accent">Company team</p><h1>People and skills</h1><p className="error-text">{error}</p></main>;
  return <main className="empty-page"><div className="team-header"><div><p className="eyebrow accent">Company team</p><h1>People and skills</h1><p className="empty-page-copy">Each profile is classified into explainable skills that help assess fit for a specific tender.</p></div>{canEdit && <button className="button" type="button" onClick={() => setShowForm((current) => !current)}>{showForm ? "Close" : "+ Add person"}</button>}</div>{showForm && <StaffForm onSaved={(member) => { setStaff((current) => [...current, member].sort((a, b) => a.display_name.localeCompare(b.display_name))); setShowForm(false); }} />}{!staff.length && !showForm ? <div className="empty-panel"><div className="empty-icon">+</div><h2>No employee profiles yet</h2><p>Add the people who may deliver work so tender fit can account for actual skills and cost.</p></div> : <div className="staff-grid">{staff.map((member) => <article className="staff-card" key={member.id}><div className="staff-card-top"><div className="avatar">{member.display_name.slice(0, 1).toUpperCase()}</div><div><h2>{member.display_name}</h2><p className="muted">{member.role_title}</p></div><span className={member.available ? "availability available" : "availability"}>{member.available ? "Available" : "Unavailable"}</span></div><p className="staff-summary">{member.skill_summary || "No skill notes added yet."}</p><div className="skill-tags">{member.classified_skills.length ? member.classified_skills.map((skill) => <span className="skill-tag" key={skill}>{labels[skill] ?? skill}</span>) : <span className="skill-tag unknown">Needs classification</span>}</div><div className="staff-card-footer"><span>{money(member.hourly_cost_cents)}/h internal cost</span>{member.skill_confidence !== null && <span>{member.skill_confidence}% classification confidence</span>}</div>{canEdit && <button className="remove-button" type="button" onClick={() => remove(member.id)}>Remove profile</button>}</article>)}</div>}</main>;
}

function StaffForm({ onSaved }: { onSaved: (member: Staff) => void }) {
  const [displayName, setDisplayName] = useState(""); const [roleTitle, setRoleTitle] = useState(""); const [skillSummary, setSkillSummary] = useState(""); const [hourlyCost, setHourlyCost] = useState(""); const [available, setAvailable] = useState(true); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); const response = await fetch("/api/team", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ displayName, roleTitle, skillSummary, hourlyCostCents: Math.round(Number(hourlyCost) * 100), available }) }); const data = await response.json(); if (!response.ok) setError(data.error ?? "Unable to save profile"); else onSaved(data.staff); setBusy(false); }
  return <form className="staff-form" onSubmit={submit}><h2>Add employee profile</h2><div className="form-grid"><label className="form-field"><span>Name</span><input value={displayName} onChange={(event) => setDisplayName(event.target.value)} placeholder="Alex Morgan" required /></label><label className="form-field"><span>Role</span><input value={roleTitle} onChange={(event) => setRoleTitle(event.target.value)} placeholder="Senior installer" required /></label><label className="form-field"><span>Skills and qualifications</span><input value={skillSummary} onChange={(event) => setSkillSummary(event.target.value)} placeholder="Drywall, gypsum, finish carpentry" /></label><label className="form-field"><span>Internal hourly cost (CAD)</span><input type="number" min="0" step="0.01" value={hourlyCost} onChange={(event) => setHourlyCost(event.target.value)} placeholder="42.00" required /></label></div><label className="available-toggle"><input type="checkbox" checked={available} onChange={(event) => setAvailable(event.target.checked)} /> Available for new work</label>{error && <p className="error-text">{error}</p>}<button className="button" disabled={busy}>{busy ? "Classifying..." : "Save employee profile"}</button></form>;
}
