"use client";

import { useEffect, useState } from "react";

type Contract = { id: string; name: string; status: string };
const pluralize = (count: number, singular: string) => `${count} ${count === 1 ? singular : `${singular}s`}`;

export default function HomePage() {
  const [tenderCount, setTenderCount] = useState<number | null>(null);
  const [contracts, setContracts] = useState<Contract[]>([]);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { Promise.all([fetch("/api/tenders"), fetch("/api/contracts")]).then(async ([tendersResponse, contractsResponse]) => { const tenders = await tendersResponse.json(); const contractData = await contractsResponse.json(); if (!tendersResponse.ok || !contractsResponse.ok) throw new Error(tenders.error ?? contractData.error ?? "Unable to load workspace"); setTenderCount((tenders.tenders ?? []).length); setContracts(contractData.contracts ?? []); }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : "Unable to load workspace")); }, []);
  const activeContracts = contracts.filter((contract) => contract.status === "bid" || contract.status === "active");
  return <main className="dashboard-content"><header className="topbar"><div><p className="eyebrow">EstimatorAI workspace</p><h1>Good morning</h1></div><div className="org-chip">Demo organization</div></header><div className="notice"><span className="notice-dot" /> {error ?? (tenderCount === null ? "Loading your workspace..." : "Your workspace is connected and ready.")}</div><section className="hero"><div><p className="eyebrow accent">Estimate with confidence</p><h2>Price the work you can win.</h2><p className="hero-copy">EstimatorAI brings public tenders, company capability, and transparent estimating into one calm workspace.</p><a className="button" href="/cost-profile">Set up cost profile <span>→</span></a></div><div className="hero-art" aria-hidden="true"><div className="art-card card-back" /><div className="art-card card-front"><span className="art-line wide" /><span className="art-line" /><span className="art-line short" /><div className="art-total">$ —</div></div></div></section><section className="section-heading"><div><p className="eyebrow">At a glance</p><h3>Your bid pipeline</h3></div><span className="muted">{tenderCount === null ? "Loading..." : `${tenderCount} tenders loaded`}</span></section><div className="metrics"><Metric label="Open tenders" value={tenderCount === null ? "—" : String(tenderCount)} detail={tenderCount ? "Available in the tender feed" : "Run the CanadaBuys ingestion worker"} /><Metric label="Potential matches" value="—" detail="Capability profile not configured" /><Metric label="Active estimates" value={String(activeContracts.length)} detail={pluralize(activeContracts.length, "contract")} /></div><section className="empty-state"><div className="empty-icon">＋</div><h3>{activeContracts.length ? "Keep your estimates auditable" : "Make your first estimate auditable"}</h3><p>{activeContracts.length ? `${pluralize(activeContracts.length, "active contract")} are in your pipeline. Review each estimate to keep assumptions, staffing, and cashflow traceable.` : "Add staff roles, crew compositions, material costs, and overheads. Every value stays editable and traceable to your company profile."}</p><a href={activeContracts.length ? "/reports" : "/cost-profile"}>{activeContracts.length ? "Open portfolio reports" : "Open cost profile"} <span>→</span></a></section></main>;
}

function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="metric"><p className="muted">{label}</p><strong>{value}</strong><p className="metric-detail">{detail}</p></article>; }
