"use client";

import { FormEvent, useEffect, useState } from "react";

const PROJECT_TYPES = [{ value: "interior-fit-out", label: "Interior fit-out" }, { value: "occupied-renovation", label: "Occupied renovation" }, { value: "restoration", label: "Restoration" }, { value: "painting", label: "Painting" }, { value: "roofing", label: "Roofing" }];
const lines = (value: string) => value.split(/\r?\n|,/).map((item) => item.trim()).filter(Boolean);

export default function SettingsPage() {
  const [buyers, setBuyers] = useState("");
  const [excluded, setExcluded] = useState("");
  const [projectTypes, setProjectTypes] = useState<string[]>([]);
  const [maximum, setMaximum] = useState("");
  const [feedbackCount, setFeedbackCount] = useState(0);
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  useEffect(() => { fetch("/api/company/match-preferences").then(async (response) => { const payload = await response.json(); if (!response.ok) throw new Error(payload.error); const value = payload.preferences; setBuyers((value.preferred_buyers ?? []).join("\n")); setExcluded((value.excluded_terms ?? []).join("\n")); setProjectTypes(value.preferred_project_types ?? []); setMaximum(value.maximum_project_size_cents == null ? "" : String(Number(value.maximum_project_size_cents) / 100)); setFeedbackCount(value.feedback_count ?? 0); }).catch((error) => setMessage(error.message)); }, []);
  function toggle(value: string) { setProjectTypes((current) => current.includes(value) ? current.filter((item) => item !== value) : [...current, value]); }
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(null); try { const response = await fetch("/api/company/match-preferences", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ preferredBuyers: lines(buyers), preferredProjectTypes: projectTypes, excludedTerms: lines(excluded), maximumProjectSizeCents: maximum ? Math.round(Number(maximum) * 100) : null }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error); setMessage("Opportunity matching rules saved. New analyses will use these preferences."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to save preferences"); } finally { setBusy(false); } }
  return <main className="empty-page settings-page"><header className="settings-header"><div><p className="eyebrow accent">Company matching rules</p><h1>Control what reaches your opportunity feed</h1><p className="empty-page-copy">These preferences refine company fit after the factual trade, geography, certification, bonding, and capacity checks. They never change tender facts or company rates.</p></div><a className="secondary-button" href="/tender-sources">Review source coverage →</a></header><form className="settings-form" onSubmit={save}><section className="profile-card"><div className="section-heading"><div><p className="eyebrow">Commercial fit</p><h2>Project size and preferred buyers</h2></div></div><div className="settings-grid"><label>Maximum preferred project value (CAD)<input type="number" min="0" step="1000" value={maximum} onChange={(event) => setMaximum(event.target.value)} placeholder="2000000" /><small>Opportunities above this value remain searchable but rank lower.</small></label><label>Preferred buyers<textarea rows={5} value={buyers} onChange={(event) => setBuyers(event.target.value)} placeholder={"City of Toronto\nToronto District School Board"} /><small>Enter one public owner per line.</small></label></div></section><section className="profile-card"><div className="section-heading"><div><p className="eyebrow">Project preference</p><h2>Work you actively want</h2></div></div><div className="preference-options">{PROJECT_TYPES.map((item) => <label className={projectTypes.includes(item.value) ? "selected" : ""} key={item.value}><input type="checkbox" checked={projectTypes.includes(item.value)} onChange={() => toggle(item.value)} /><span>{item.label}</span></label>)}</div></section><section className="profile-card"><div className="section-heading"><div><p className="eyebrow">Hard exclusions</p><h2>Work to keep out of the main feed</h2></div></div><label className="settings-textarea">Excluded words or work types<textarea rows={6} value={excluded} onChange={(event) => setExcluded(event.target.value)} placeholder={"new build\nbridge\nheavy civil\nasbestos abatement"} /><small>When an excluded phrase is detected, the opportunity is marked not viable but remains available under “All scanned.”</small></label></section><div className="settings-save"><div><strong>{feedbackCount} relevance decision(s)</strong><span>Yes/no feedback on opportunities is also used as bounded company-specific ranking evidence.</span></div><button className="button" type="submit" disabled={busy}>{busy ? "Saving…" : "Save matching rules"}</button></div>{message && <p className="auth-message" role="status">{message}</p>}</form></main>;
}
